### ISSUE TITLE
The stratified function gives surprising results

### ISSUE THREAD

**Issue by CMagnusE** [mrdwab/splitstackshape#47]
I didn't expect to get a result like the one below:

> df<-data.frame(x=c(1,1,2,2,2,7),t=1:6)
> df
>   x t
> 1 1 1
> 2 1 2
> 3 2 3
> 4 2 4
> 5 2 5
> 6 7 6
> stratified(df,group=1,size=1)
>    x t
> 1: 1 1
> 2: 2 5
> 3: 1 1

I expected to get exactly one row of values from stratum "1", "2", and "7", respectively. Instead, I got two from "1", one from "2", and none from "7".

How is this possible? Have I misunderstood something?

Best regards,
Magnus

**Comment by mrdwab** [comment]
@CMagnusE , Thanks for raising the issue. I'll have to look into this and see if I can find out where the problem emerges. It seems to be something that happened when I transitioned the function to `data.table` instead of having it be based on `data.frame`s, so I'll have to check against more recent versions. In the meantime, I could suggest `sample_n` from "dplyr" as a reliable alternative.

**Comment by mrdwab** [comment]
Fixed in https://github.com/mrdwab/splitstackshape/commit/1407ad9fc8132b63d125b9d61276b0d5121864ff.

**Comment by mrdwab** [comment]
Should add the commit to the 1.4.5 branch too and then close.

**Comment by mrdwab** [comment]
Fixed in https://github.com/mrdwab/splitstackshape/commit/a3a3fd0c7eb5397159f7f970ab85ff4a85136116.
